Repository scala/improvement-proposals, pull requests merged in 2024-08, with the labels that each got.

#72 SIP-58 - Named Tuples
  content/named-tuples.md
Labels: stage:implementation, status:waiting-for-implementation, manager:lihaoyi

#84 Match types amendment: extractors follow aliases and singletons
  content/match-types-spec.md
Labels: status:under-review, stage:implementation, manager:sjrd

#81 SIP-64: Improve the Syntax of Context Bounds and Givens
  content/typeclasses-syntax.md
Labels: status:under-review, stage:implementation, manager:sjrd

#79 SIP-62 - For comprehension improvements
  content/better-fors.md
Labels: stage:implementation, status:waiting-for-implementation, manager:lihaoyi

#78 SIP-61 - Unroll Default Arguments for Binary Compatibility
  content/unroll-default-arguments.md
Labels: stage:implementation, status:waiting-for-implementation, manager:lrytz

#74 SIP-60 - Alternative bind patterns
  content/alternative-bind-variables.md
Labels: stage:implementation, status:waiting-for-implementation, manager:smarter

#73 SIP-59 - Multiple assignments
  content/multiple-assignments.md
Labels: stage:implementation, status:waiting-for-implementation, manager:sjrd
